In [1]:
#Importação de bibliotecas 
import numpy as np #np será o apelido 

In [2]:
temperaturas = np.array([30,40,50,60,70,80,90,100])
print(temperaturas)
print(type(temperaturas))

[ 30  40  50  60  70  80  90 100]
<class 'numpy.ndarray'>


In [3]:
#Média aritimética
media = np.mean(temperaturas)
print(f"{media:.2f}")

65.00


In [4]:
maior_valor = np.max(temperaturas)
print(maior_valor)

100


In [5]:
menor_valor = np.min(temperaturas)
print(menor_valor)

30


In [6]:
salarios = np.array([2,3,4,5,1,500])
media_salarios = np.mean(salarios)
print(media_salarios)

85.83333333333333


In [7]:
mediana = np.median(salarios)
print(mediana)

3.5


In [9]:
import numpy as sp

In [10]:
cidades = sp.array([1190961,1291784,1138309,810729,748919])

print(cidades)

maior_populacao = sp.max(cidades)
print(f"O valor da maior população é: {maior_populacao}")

menor_populacao = sp.min(cidades)
print(f"O valor da menor população é: {menor_populacao}")

media_populacao = sp.mean(cidades)
print(f"A média de população é: {media_populacao}")

mediana = sp.median(cidades)
print(f"A mediana é: {mediana}")

[1190961 1291784 1138309  810729  748919]
O valor da maior população é: 1291784
O valor da menor população é: 748919
A média de população é: 1036140.4
A mediana é: 1138309.0


In [20]:
numeros = np.array([2,3,4,5,6,7,8])
print(np.array(numeros))

[2 3 4 5 6 7 8]


In [21]:
conjunto = np.median([2,3,4,5,6,7,8])
print(np.median(conjunto))

5.0
